using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Garoa.SourceGenerator;

/// <summary>
/// Emits a compile-time <c>IGaroaRowMapper&lt;T&gt;</c> for every type annotated with
/// <c>[GaroaMapped]</c>. The generated mapper reads each member through a typed reader getter
/// (<c>GetInt64</c>, <c>GetString</c>, …) where the BCL provides one, and falls back to
/// <c>GetFieldValue&lt;T&gt;</c> for types the provider must resolve itself (e.g. DateOnly).
/// It self-registers via a module initializer so the runtime picks it up automatically.
/// </summary>
[Generator(Microsoft.CodeAnalysis.LanguageNames.CSharp)]
public sealed class MapperGenerator : IIncrementalGenerator
{
    private const string MarkerAttribute = "Garoa.GaroaMappedAttribute";
    private const string ColumnAttribute = "Garoa.ColumnAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<MapperModel?> models = context.SyntaxProvider.ForAttributeWithMetadataName(
            MarkerAttribute,
            predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
            transform: static (ctx, _) => BuildModel((INamedTypeSymbol)ctx.TargetSymbol));

        context.RegisterSourceOutput(models.Where(static m => m is not null), static (spc, model) => Emit(spc, model!));
    }

    private static MapperModel? BuildModel(INamedTypeSymbol type)
    {
        // v1 supports non-generic concrete types with an accessible parameterless constructor.
        if (type.IsAbstract || type.IsGenericType)
            return null;

        bool hasParameterlessCtor = type.IsValueType || type.InstanceConstructors.Any(c =>
            c.Parameters.Length == 0 &&
            c.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal);
        if (!hasParameterlessCtor)
            return null;

        var members = new List<MemberModel>();
        var seen = new HashSet<string>();

        // Properties first (matching the runtime mapper's "first declaration wins" ordering),
        // then fields.
        foreach (ISymbol member in type.GetMembers())
        {
            if (member is IPropertySymbol prop)
            {
                if (prop.IsStatic || prop.IsIndexer || prop.SetMethod is null)
                    continue;
                if (prop.SetMethod.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
                    continue;
                TryAddMember(members, seen, member, prop.Name, prop.Type);
            }
        }

        foreach (ISymbol member in type.GetMembers())
        {
            if (member is IFieldSymbol field)
            {
                if (field.IsStatic || field.IsReadOnly || field.IsConst || field.IsImplicitlyDeclared)
                    continue;
                if (field.DeclaredAccessibility != Accessibility.Public)
                    continue;
                TryAddMember(members, seen, member, field.Name, field.Type);
            }
        }

        if (members.Count == 0)
            return null;

        return new MapperModel(type, members.ToImmutableArray());
    }

    private static void TryAddMember(
        List<MemberModel> members, HashSet<string> seen, ISymbol member, string memberName, ITypeSymbol memberType)
    {
        string columnName = ColumnNameOf(member) ?? memberName;
        string key = Normalize(columnName);
        if (!seen.Add(key))
            return;

        members.Add(new MemberModel(member.Name, key, memberType));
    }

    private static string? ColumnNameOf(ISymbol member)
    {
        foreach (AttributeData attr in member.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() == ColumnAttribute &&
                attr.ConstructorArguments.Length == 1 &&
                attr.ConstructorArguments[0].Value is string name)
            {
                return name;
            }
        }

        return null;
    }

    private static void Emit(SourceProductionContext context, MapperModel model)
    {
        INamedTypeSymbol type = model.Type;
        string targetFq = type.ToDisplayString(FqFormat);
        string mapperName = SanitizeName(type) + "RowMapper";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8619, CS8625");
        sb.AppendLine();
        sb.AppendLine("namespace Garoa.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    internal sealed class {mapperName} : global::Garoa.IGaroaRowMapper<{targetFq}>");
        sb.AppendLine("    {");

        // ResolveSlot: normalized column name -> member slot.
        sb.AppendLine("        public int ResolveSlot(string normalizedColumn) => normalizedColumn switch");
        sb.AppendLine("        {");
        for (int i = 0; i < model.Members.Length; i++)
            sb.AppendLine($"            \"{model.Members[i].ColumnKey}\" => {i},");
        sb.AppendLine("            _ => -1,");
        sb.AppendLine("        };");
        sb.AppendLine();

        // Map: typed reads per slot, with a column-accurate catch.
        sb.AppendLine($"        public {targetFq} Map(global::System.Data.Common.DbDataReader reader, int[] slots)");
        sb.AppendLine("        {");
        sb.AppendLine("            int __ordinal = 0;");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine($"                var __result = new {targetFq}();");
        sb.AppendLine("                for (__ordinal = 0; __ordinal < slots.Length; __ordinal++)");
        sb.AppendLine("                {");
        sb.AppendLine("                    switch (slots[__ordinal])");
        sb.AppendLine("                    {");
        for (int i = 0; i < model.Members.Length; i++)
        {
            MemberModel m = model.Members[i];
            sb.AppendLine($"                        case {i}: __result.{m.MemberName} = {ReadExpression(m.Type)}; break;");
        }
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("                return __result;");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (global::System.Exception __ex)");
        sb.AppendLine("            {");
        sb.AppendLine($"                throw global::Garoa.GaroaGeneratedMappers.MappingError(reader, __ordinal, typeof({targetFq}), __ex);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Self-registration at module load.
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void __Register()");
        sb.AppendLine($"            => global::Garoa.GaroaGeneratedMappers.Register<{targetFq}>(new {mapperName}());");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{mapperName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    // Builds: reader.IsDBNull(__ordinal) ? default(MT) : <typed read>
    private static string ReadExpression(ITypeSymbol memberType)
    {
        string memberFq = memberType.ToDisplayString(FqFormat);
        ITypeSymbol underlying = UnwrapNullable(memberType);
        string underlyingFq = underlying.ToDisplayString(FqFormat);

        string read;
        if (underlying.TypeKind == TypeKind.Enum && underlying is INamedTypeSymbol enumType)
        {
            string numericFq = enumType.EnumUnderlyingType!.ToDisplayString(FqFormat);
            read = $"({underlyingFq})reader.GetFieldValue<{numericFq}>(__ordinal)";
        }
        else if (TypedGetter(underlying) is { } getter)
        {
            read = $"reader.{getter}(__ordinal)";
        }
        else
        {
            read = $"reader.GetFieldValue<{underlyingFq}>(__ordinal)";
        }

        return $"reader.IsDBNull(__ordinal) ? default({memberFq}) : {read}";
    }

    private static ITypeSymbol UnwrapNullable(ITypeSymbol type) =>
        type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } named
            ? named.TypeArguments[0]
            : type;

    // Typed DbDataReader getters for the types the BCL exposes one for. Anything else (DateOnly,
    // TimeOnly, DateTimeOffset, byte[], custom types) goes through GetFieldValue<T> so the provider
    // resolves it — the same delegation that lets Garoa read DateOnly natively.
    private static string? TypedGetter(ITypeSymbol type) => type.SpecialType switch
    {
        SpecialType.System_Boolean => "GetBoolean",
        SpecialType.System_Byte => "GetByte",
        SpecialType.System_Int16 => "GetInt16",
        SpecialType.System_Int32 => "GetInt32",
        SpecialType.System_Int64 => "GetInt64",
        SpecialType.System_Single => "GetFloat",
        SpecialType.System_Double => "GetDouble",
        SpecialType.System_Decimal => "GetDecimal",
        SpecialType.System_String => "GetString",
        SpecialType.System_DateTime => "GetDateTime",
        SpecialType.System_Char => "GetChar",
        _ => type.ToDisplayString() == "System.Guid" ? "GetGuid" : null,
    };

    private static string SanitizeName(INamedTypeSymbol type)
    {
        string full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (full.StartsWith("global::", System.StringComparison.Ordinal))
            full = full.Substring("global::".Length);

        var sb = new StringBuilder(full.Length);
        foreach (char c in full)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.ToString();
    }

    // Mirrors Garoa.Mapping.TypeHelper.NormalizeName: lower-cased, underscores stripped.
    private static string Normalize(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (char c in name)
        {
            if (c == '_') continue;
            sb.Append(char.ToLowerInvariant(c));
        }

        return sb.ToString();
    }

    private static readonly SymbolDisplayFormat FqFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(
                SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private sealed class MapperModel
    {
        public MapperModel(INamedTypeSymbol type, ImmutableArray<MemberModel> members)
        {
            Type = type;
            Members = members;
        }

        public INamedTypeSymbol Type { get; }
        public ImmutableArray<MemberModel> Members { get; }
    }

    private sealed class MemberModel
    {
        public MemberModel(string memberName, string columnKey, ITypeSymbol type)
        {
            MemberName = memberName;
            ColumnKey = columnKey;
            Type = type;
        }

        public string MemberName { get; }
        public string ColumnKey { get; }
        public ITypeSymbol Type { get; }
    }
}
